name: pytorch_mobile
description: A flutter plugin for pytorch model inference. Supports image models as well as custom models.
version: 0.3.0
homepage: https://github.com/fynnmaarten/flutter_pytorch_mobile

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.2
  path: ^1.8.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: io.fynn.pytorch_mobile
        pluginClass: PyTorchMobilePlugin
      ios:
        pluginClass: PyTorchMobilePlugin
